// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Callbag$BsCallbag = require("./Callbag.bs.js");

Callbag$BsCallbag.observe((function (d) {
        console.log(d);
        return /* () */0;
      }), (function (param) {
        return Callbag$BsCallbag.take(2, (function (param) {
                      return Callbag$BsCallbag.interval(1000, param);
                    }), param);
      }));

/*  Not a pure module */
